# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_screenshots_and_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=128)),
                ('url', models.URLField()),
                ('icon', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='contacts')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
