# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-30 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20160311_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='short_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
